# Databricks notebook source
# DBTITLE 1,Create schema for the project
# MAGIC %sql
# MAGIC -- Create schema if it does not exist
# MAGIC CREATE SCHEMA IF NOT EXISTS chatbot

# COMMAND ----------

# DBTITLE 1,Create table to hold extracted pdf text
# MAGIC %sql
# MAGIC -- Create table to store text extracted from PDF files
# MAGIC CREATE TABLE IF NOT EXISTS workspace.chatbot.docs_text (
# MAGIC   id BIGINT GENERATED BY DEFAULT AS IDENTITY, -- Unique identifier for each text entry
# MAGIC   text STRING -- Extracted text content from PDF files
# MAGIC ) tblproperties (delta.enableChangeDataFeed = true);

# COMMAND ----------

# DBTITLE 1,Create table to track which pdf files we've already processed
# MAGIC %sql
# MAGIC -- Create table to track PDF files processed
# MAGIC CREATE TABLE IF NOT EXISTS workspace.chatbot.docs_track (
# MAGIC   file_name STRING -- Name of the PDF file
# MAGIC ) tblproperties (delta.enableChangeDataFeed = true);

# COMMAND ----------

# Directory path
directory_path = "/Volumes/workspace/chatbot/source_docs"

# Create the volume
spark.sql("""
CREATE VOLUME IF NOT EXISTS workspace.chatbot
COMMENT 'Volume for chatbot workspace'
""")

# Create the directory
dbutils.fs.mkdirs(directory_path)
